### ISSUE TITLE
Dedicated tab for recent floor votes

### ISSUE THREAD

**Issue by the-graphics-project** [nysenate/NYSenate.gov#34]
Currently, the NYS Senate website lacks a proper and dedicated tab that displays all of the results of floor votes (that includes bills, amendments, motions, and confirmation votes). I think this would be a very useful feature to add and it would add another layer of transparency and clarity on things. For reference, the U.S. Senate’s website has a dedicated section for votes. Please consider this addition! Thanks.

**Comment by routinet** [comment]
I almost forgot to mention: voting information is exposed on www.nysenate.gov, but it is really only accessible at the bill/resolution level.  At the same time, the daily agenda/calendars contain links to the items being addressed.  With a little leg work, it is absolutely possible to find all votes from a particular day.

Admittedly, this is less than ideal, and the implementation being planned for this issue is along the lines of better discovery/aggregation of the underlying data.
